apiVersion: config.example.com/v1alpha1
kind: Config
metadata:
  name: test
  namespace: default
  labels:
    targetName: dev1
    targetNamespace: default
spec:
  priority: 10
  config:
  - path: /
    value:
      interface:
      - name: "system0"
        admin-state: "enable"
        description: "k8s-system0-dummy"