kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-apiserver-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources: ["flowschemas", "prioritylevelconfigurations"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["config.example.com"]
  resources: ["configs", "configs/status"]
  verbs: ["create","update","patch","get", "watch", "list"]

