kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregated-apiserver-role
  namespace: network-system
rules:
  # Needed for workload identity
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
